image:
  repository: gcr.io/prysmaticlabs/prysm/validator
  tag: latest

replicas: 1

config:
  datadir: /data
  p2p-tcp-port: 13000
  beacon-rpc-provider: prysm-beacon:4000
  log-file: /data/validator.log
  verbosity: info

# A list of secrets and their paths to mount inside the initContainer
# initContainer will copy these to /data/wallet to be available
# in the main container
secretMounts: []
#  - name: keymanageropts
#    secretName: keymanageropts
#    mountPath: /data/mount/direct
#  - name: keystore
#    secretName: keystore
#    mountPath: /data/mount/direct/accounts
#  - name: password
#    secretName: password
#    mountPath: /data/mount/password

storage:
  capacity: 1Gi

resources:
  limits:
    memory: 1Gi
  requests:
    memory: 1Gi