image:
  repository: gcr.io/prysmaticlabs/prysm/validator
  tag: latest

replicas: 1

config:
  datadir: /data
  p2p-tcp-port: 13000
  beacon-rpc-provider: prysm-beacon:4000
  log-file: /data/validator.log
  verbosity: info

storage:
  capacity: 1Gi

resources:
  limits:
    memory: 1Gi
  requests:
    memory: 1Gi