{{- if .Values.config }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "prysm-validator.fullname" . }}-config
data:
  validator.yaml: |
{{ toYaml .Values.config | indent 4 }}
{{- end }}