apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ template "prysm-validator.fullname" . }}
  labels:
    {{- include "prysm-validator.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
    {{- include "prysm-validator.selectorLabels" . | nindent 6 }}
  serviceName: {{ template "prysm-validator.fullname" . }}
  replicas: {{ .Values.replicas }}
  template:
    metadata:
      labels:
      {{- include "prysm-validator.labels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          {{- if .Values.config }}
          args: ["--config-file","/data/config/validator.yaml"]
          {{- end }}
          resources: 
{{ toYaml .Values.resources | indent 12 }}
          livenessProbe:
            failureThreshold: 60
            httpGet:
              path: /healthz
              port: {{ (index .Values "config" "monitoring-port") | default 8080 }}
            initialDelaySeconds: 60
            periodSeconds: 60
            timeoutSeconds: 5
          volumeMounts:
            - name: validator-data
              mountPath: /data
            - name: keymanageropts
              mountPath: /wallet/direct
              readOnly: true
            - name: keystore
              mountPath: /wallet/direct/accounts
              readOnly: true
            - name: password
              mountPath: /wallet/password
              readOnly: true
            {{- if .Values.config }}
            - name: config
              mountPath: /data/config
            {{- end }}
          ports:
            - name: p2p-tcp
              containerPort: {{ (index .Values "config" "p2p-tcp-port") | default 13000 }}
            - name: p2p-udp
              containerPort: {{ (index .Values "config" "p2p-udp-port") | default 12000 }}
            - name: monitoring
              containerPort: {{ (index .Values "config" "monitoring-port") | default 8080 }}
      volumes:
        {{- if .Values.config }}
        - name: config
          configMap:
            name: {{ template "prysm-validator.fullname" . }}-config
        {{- end }}
        - name: keymanageropts
          secret:
            secretName: keymanageropts
        - name: keystore
          secret:
            secretName: keystore
        - name: password
          secret:
            secretName: password
  volumeClaimTemplates:
    - metadata:
        name: validator-data
      spec:
        storageClassName: manual
        accessModes: 
          - "ReadWriteOnce"
        resources:
          requests:
            storage: {{ .Values.storage.capacity | quote }}