{{- if .Values.servicemonitor.enabled -}}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ template "prysm-validator.fullname" . }}
  labels:
    {{- include "prysm-validator.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "prysm-validator.selectorLabels" . | nindent 4 }}
  endpoints:
  - port: metrics
{{- end }}