{{- if .Values.servicemonitor.enabled -}}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ template "prysm-validator.fullname" . }}-slasher
  labels:
    {{- include "prysm-validator.labels" . | nindent 4 }}-slasher
spec:
  selector:
    matchLabels:
      app: {{ template "prysm-validator.name" . }}-slasher
  endpoints:
  - port: metrics
{{- end }}