apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ template "prysm-beacon.fullname" . }}-data
  labels:
    {{- include "prysm-beacon.labels" . | nindent 4 }}
  annotations:
    "helm.sh/resource-policy": keep
spec:
  storageClassName: manual
  persistentVolumeReclaimPolicy: Retain
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: {{ .Values.storage.capacity | quote }}
  hostPath:
    path: /data