apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ template "prysm-beacon.fullname" . }}-slasher-data
  labels:
    app: {{ template "prysm-beacon.name" . }}-slasher
    {{- include "prysm-beacon.labels" . | nindent 4 }}
  annotations:
    "helm.sh/resource-policy": keep
spec:
  storageClassName: manual
  persistentVolumeReclaimPolicy: Retain
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: {{ .Values.slasher.storage.capacity }}
  hostPath:
    path: /data