apiVersion: v1
kind: Service
metadata:
  name: {{ include "prysm-beacon.fullname" . }}
  labels: 
    {{- include "prysm-beacon.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "prysm-beacon.selectorLabels" . | nindent 4 }}
  ports:
    - protocol: TCP
      port: {{ (index .Values "config" "p2p-tcp-port") | default 13000 }}
      name: p2p-tcp
    - protocol: UDP
      port: {{ (index .Values "config" "p2p-udp-port") | default 12000 }}
      name: p2p-udp
    - protocol: TCP
      port: {{ (index .Values "config" "metrics-port") | default 8080 }}
      name: metrics
    - protocol: TCP
      port: {{ (index .Values "config" "rpc-port") | default 4000 }}
      name: rpc