---
image: gcr.io/prysmaticlabs/prysm/beacon-chain
imageTag: latest

replicas: 1

containerArgs:
  - "--config-file"
  - "/data/config/beacon-client.yaml"

config:
  datadir: ./data
  p2p-tcp-port: 13000
  log-file: /data/beacon.log
  verbosity: info

storage:
  capacity: "20Gi"

resources:
  limits:
    memory: "8Gi"
  requests:
    memory: "4Gi"

slasher:
  enabled: false

  image:
    repository: gcr.io/prysmaticlabs/prysm/slasher
    tag: latest

  args:
    - --beacon-rpc-provider=beacon-client:4000
    - --datadir=/data
    - --rpc-host=0.0.0.0
    - --monitoring-host=0.0.0.0

  storage:
    capacity: 3Gi

  ports:
    metrics: 8082
    rpc: 4002

  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      cpu: 100m
      memory: 256Mi